/**
 * Arithmetic over GF(256), the field QR error correction is defined on.
 *
 * The field is generated by the primitive polynomial x^8 + x^4 + x^3 + x^2 + 1
 * (0x11D), fixed by ISO/IEC 18004 §7.5.2. Multiplication goes through log and
 * antilog tables because the alternative — carry-less multiply plus modular
 * reduction on every operation — is roughly an order of magnitude slower, and
 * Reed-Solomon encoding runs this in its innermost loop.
 */

const PRIMITIVE = 0x11d;

const EXP = new Uint8Array(256);
const LOG = new Uint8Array(256);

{
  let x = 1;
  for (let i = 0; i < 256; i++) {
    EXP[i] = x;
    x <<= 1;
    if (x & 0x100) x ^= PRIMITIVE;
  }
  // EXP cycles with period 255, so EXP[255] === EXP[0] === 1 and only indices
  // 0..254 carry distinct values worth inverting. LOG[0] stays 0 and is never
  // read: `mul` short-circuits on a zero operand.
  for (let i = 0; i < 255; i++) LOG[EXP[i]] = i;
}

export const mul = (a: number, b: number): number =>
  a === 0 || b === 0 ? 0 : EXP[(LOG[a] + LOG[b]) % 255];

/**
 * Reed-Solomon generator polynomials, keyed by degree.
 *
 * Only about a dozen distinct degrees appear across the whole version/level
 * table, and generating one is O(degree^2). Caching turns repeated encodes —
 * a batch run, or the eight mask trials inside a single encode — into table
 * lookups. Values are never mutated after construction, so sharing is safe.
 */
const DIVISORS = new Map<number, Uint8Array>();

/**
 * Build the Reed-Solomon generator polynomial of the given degree: the product
 * of (x - a^i) for i in [0, degree). Returned in descending powers with the
 * leading coefficient (always 1) omitted, which is what the remainder loop
 * wants.
 *
 * The returned array is shared and must not be mutated.
 */
export const computeDivisor = (degree: number): Uint8Array => {
  const cached = DIVISORS.get(degree);
  if (cached) return cached;

  if (degree < 1 || degree > 255) {
    throw new RangeError(`Reed-Solomon degree out of range: ${degree}`);
  }

  const result = new Uint8Array(degree);
  result[degree - 1] = 1;

  let root = 1;
  for (let i = 0; i < degree; i++) {
    for (let j = 0; j < degree; j++) {
      result[j] = mul(result[j], root);
      if (j + 1 < degree) result[j] ^= result[j + 1];
    }
    root = mul(root, 0x02);
  }

  DIVISORS.set(degree, result);
  return result;
};

/**
 * Remainder of `data` divided by `divisor` — the error correction codewords.
 *
 * When `out` is supplied it is filled and returned, letting the caller reuse
 * one scratch buffer across every block of a symbol instead of allocating per
 * block.
 */
export const computeRemainder = (
  data: Uint8Array,
  divisor: Uint8Array,
  out?: Uint8Array,
): Uint8Array => {
  const result = out ?? new Uint8Array(divisor.length);
  if (out) out.fill(0);

  for (const byte of data) {
    const factor = byte ^ result[0];
    result.copyWithin(0, 1);
    result[result.length - 1] = 0;
    if (factor !== 0) {
      // Skipping a zero factor is worth a branch: pad codewords and runs of
      // zero bytes are common, and `mul` would return 0 for every term.
      const logFactor = LOG[factor];
      for (let i = 0; i < result.length; i++) {
        const d = divisor[i];
        if (d !== 0) result[i] ^= EXP[(LOG[d] + logFactor) % 255];
      }
    }
  }

  return result;
};

/** Multiplicative inverse. Throws on zero, which has none. */
export const inv = (a: number): number => {
  if (a === 0) throw new RangeError('GF(256) has no inverse for 0');
  return EXP[(255 - LOG[a]) % 255];
};

/** Division in GF(256). */
export const div = (a: number, b: number): number => {
  if (b === 0) throw new RangeError('GF(256) division by 0');
  return a === 0 ? 0 : EXP[(LOG[a] + 255 - LOG[b]) % 255];
};

/** `a^exponent`, with `a` a field element and `exponent` any integer. */
export const pow = (a: number, exponent: number): number => {
  if (a === 0) return exponent === 0 ? 1 : 0;
  return EXP[(((LOG[a] * exponent) % 255) + 255) % 255];
};

/** Evaluate a polynomial (descending powers) at `x` using Horner's rule. */
export const polyEval = (poly: ArrayLike<number>, x: number): number => {
  let y = 0;
  for (let i = 0; i < poly.length; i++) y = mul(y, x) ^ poly[i];
  return y;
};
