import type { Command } from 'commander';
import { registerAppCommand } from './app';
import { registerComponentCommand } from './component';
import { registerDoctorCommand } from './doctor';
import { registerEnvCommand } from './env';
import { registerFeatureCommand } from './feature';
import { registerHookCommand } from './hook';
import { registerLayoutCommand } from './layout';
import { registerLocaleCommand } from './locale';
import { registerPageCommand } from './page';
import { registerProviderCommand } from './provider';
import { registerRemoveCommand } from './remove';
import { registerServiceCommand } from './service';
import { registerSetupCommand } from './setup';
import { registerSliceCommand } from './slice';
import { registerTestCommand } from './test';

export const registerCommands = (program: Command) => {
  registerAppCommand(program);
  registerSetupCommand(program);
  registerFeatureCommand(program);
  registerSliceCommand(program);
  registerServiceCommand(program);
  registerPageCommand(program);
  registerLayoutCommand(program);
  registerComponentCommand(program);
  registerLocaleCommand(program);
  registerHookCommand(program);
  registerProviderCommand(program);
  registerEnvCommand(program);
  registerDoctorCommand(program);
  registerRemoveCommand(program);
  registerTestCommand(program);
};
