export const PROJECT_PATHS = {
  // Config
  NEXT_CONFIG: 'next.config.ts',
  TAILWIND_CONFIG: 'tailwind.config.ts',
  POSTCSS_CONFIG: 'postcss.config.mjs',
  ESLINT_CONFIG: 'eslint.config.mjs',
  TS_CONFIG: 'tsconfig.json',
  PACKAGE_JSON: 'package.json',
  ENV_EXAMPLE: '.env.example',
  GITIGNORE: '.gitignore',
  README: 'README.md',
  LICENSE: 'LICENSE',
  CHANGELOG: 'CHANGELOG.md',
  NVM_RC: '.nvmrc',
  NPM_RC: '.npmrc',

  // Source
  SRC: 'src',
  APP: 'src/app',
  COMPONENTS: 'src/components',
  LIB: 'src/lib',
  PROVIDERS: 'src/providers',
  STYLES: 'src/styles',
  TYPES: 'src/types',
  UTILS: 'src/lib/utils',
  HOOKS: 'src/hooks',
  SERVICES: 'src/services',
  STORE: 'src/store',
  I18N: 'src/i18n',

  // Specific Files
  GLOBALS_CSS: 'src/styles/globals.css',
  ROOT_LAYOUT: 'src/app/layout.tsx',
  ROOT_PAGE: 'src/app/page.tsx',
  ROOT_PROVIDER: 'src/providers/RootProvider.tsx',
  PROVIDERS_INDEX: 'src/providers/index.ts',
  COMPONENTS_INDEX: 'src/components/index.ts',
  TYPES_INDEX: 'src/types/index.ts',
  UTILS_INDEX: 'src/lib/utils/index.ts',
  CONFIG_INDEX: 'src/lib/config/index.ts',
  CONSTANTS: 'src/lib/config/constants.ts',
  APP_LOCALES: 'src/lib/config/app-locales.ts',
  MIDDLEWARE: 'src/middleware.ts',
  PROXY: 'src/proxy.ts',
  I18N_TYPES: 'src/types/i18n.ts',

  // Directories to Cleanup
  HTTP_UTILS: 'src/lib/utils/http',
  AXIOS_CLIENT: 'src/lib/utils/http/axios-client',
  FETCH_CLIENT: 'src/lib/utils/http/fetch-client',
  AXIOS_CLIENT_FILE: 'src/lib/utils/http/axios-client/index.ts',
  FETCH_CLIENT_FILE: 'src/lib/utils/http/fetch-client/index.ts',
  CLIENT_UTILS: 'src/lib/utils/http/client-utils.ts',
  APP_APIS: 'src/lib/config/app-apis.ts',
  STORAGE_SERVICE: 'src/services/storage',
  COUNTER_FEATURE: 'src/features/counter',
  I18N_DIR: 'src/i18n',
  LOCALE_DIR: 'src/app/[locale]',
  ERRORS_DIR: 'src/lib/errors',
  UTILITY_TYPES_DIR: 'src/types/utility',
  COMMON_TYPES_DIR: 'src/types/common',
  HTTP_TYPES: 'src/types/common/http.types.ts',
  GITHUB_DIR: '.github',
  HUSKY_DIR: '.husky',
  STORE_PROVIDER: 'src/providers/StoreProvider.tsx',
  THEME_PROVIDER: 'src/providers/CustomThemeProvider.tsx',
  COUNTER_COMPONENT: 'src/features/counter/components/Counter.tsx',
  LOCALE_PAGE: 'src/app/[locale]/page.tsx',

  // Config files
  COMMITLINT_CONFIG: 'commitlint.config.mjs',
  LINTSTAGED_RC: '.lintstagedrc.mjs',
  CZRC: '.czrc',
  DOCKERIGNORE: '.dockerignore',
  DOCKERFILE: 'Dockerfile',
  DOCKER_COMPOSE: 'docker-compose.yml',

  // GitHub
  GITHUB_WORKFLOWS: '.github/workflows',
  GITHUB_ISSUE_TEMPLATE: 'ISSUE_TEMPLATE',
  GITHUB_PR_TEMPLATE: 'PULL_REQUEST_TEMPLATE.md',

  // Community files
  CODE_OF_CONDUCT: 'CODE_OF_CONDUCT.md',
  CONTRIBUTING: 'CONTRIBUTING.md',
  SECURITY: 'SECURITY.md',
} as const;
