import { describe, expect, it } from 'vitest';
import * as core from '../src/core.js';
import * as exportEntry from '../src/export.js';
import * as index from '../src/index.js';
import * as kanji from '../src/kanji.js';
import * as payload from '../src/payload.js';
import * as raster from '../src/raster.js';
import * as render from '../src/render.js';
import * as terminal from '../src/terminal.js';
import * as validate from '../src/validate.js';
import * as verify from '../src/verify.js';

/**
 * A snapshot of everything the package exports, per entry point.
 *
 * Not a style check — a mechanism. "We have settled what the API is" is a
 * claim that decays the moment someone adds an `export` to a barrel file
 * without noticing, and this package has eleven of them. Freezing the list
 * means any change to the public surface has to be made here too, deliberately
 * and in the same commit, where a reviewer will see it.
 *
 * Adding a name is fine and additive; **removing** one is a breaking change and
 * the failure here is the reminder. Updating this file is the normal thing to
 * do, ignoring the failure is not.
 *
 * See the README's stability section for which of these names carry a
 * compatibility promise: the documented API does, the exposed internals below
 * it do not.
 */
const SURFACE: Record<string, string[]> = {
  teiqr: [
    'ALPHANUMERIC_CHARSET',
    'BUILTIN_RULES',
    'BitWriter',
    'COMFORTABLE_CONTRAST',
    'CONNECTED_SHAPES',
    'DEFAULT_FRAME',
    'DEFAULT_STYLE',
    'ECC_ORDER',
    'ECC_RECOVERY',
    'ECI',
    'EMPTY_BITS',
    'EYE_BALL_SAFETY',
    'EYE_FRAME_SAFETY',
    'GROUP_LABEL',
    'LABEL_HEIGHT',
    'LOGO_BUDGET_WARN',
    'MASK_FUNCTIONS',
    'MAX_ECI',
    'MAX_SYMBOLS',
    'MAX_VERSION',
    'MICRO_LEVELS',
    'MICRO_MASK_FUNCTIONS',
    'MICRO_VERSIONS',
    'MIN_CONTRAST',
    'MIN_VERSION',
    'MODULE',
    'MODULE_SHAPE_SAFETY',
    'NotFoundError',
    'PAYLOAD_GROUPS',
    'PAYLOAD_TYPES',
    'QrCapacityError',
    'RMQR_SPECS',
    'RMQR_VERSIONS',
    'Raster',
    'SAFETY_EVIDENCE',
    'SAFETY_NOTE',
    'UncorrectableError',
    'adler32',
    'alignmentPatternPositions',
    'binarize',
    'bitAt',
    'blockLayout',
    'bodyPath',
    'buildMatrix',
    'buildScene',
    'buildSegments',
    'byteCapacity',
    'capacityBits',
    'circlePath',
    'clone',
    'computeDivisor',
    'computeRemainder',
    'contrastRatio',
    'correct',
    'countBits',
    'coverageReport',
    'crc32',
    'dataModuleSequence',
    'decodeLocation',
    'decodeMatrix',
    'decodeMicroMatrix',
    'decodePng',
    'decodeRmqrMatrix',
    'deflateRaw',
    'div',
    'eccCodewordsPerBlock',
    'eciDesignator',
    'eciWidth',
    'encode',
    'encodeMicro',
    'encodePng',
    'encodeRmqr',
    'encodeStructured',
    'escapeAttr',
    'escapeMeCard',
    'escapeVCard',
    'escapeWifi',
    'eyeBallPath',
    'eyeFramePath',
    'eyeOrigins',
    'fillColors',
    'findFinders',
    'formatBits',
    'functionPatternKinds',
    'getKanjiTable',
    'getPayloadType',
    'groupFinders',
    'hashString',
    'inflateZlib',
    'inv',
    'isAlphanumeric',
    'isCountlessMode',
    'isInverted',
    'isKanjiAvailable',
    'isNumeric',
    'isPayloadComplete',
    'joinStructured',
    'locateSymbols',
    'logoGeometry',
    'luminance',
    'makeAlphanumericSegment',
    'makeByteSegment',
    'makeEciSegment',
    'makeKanjiSegment',
    'makeNumericSegment',
    'makePaint',
    'makeSegments',
    'microDataBits',
    'microFormatBits',
    'microModeBits',
    'microModel',
    'microSize',
    'microVersionOf',
    'modeIndicator',
    'mul',
    'normalizePhone',
    'normalizeUrl',
    'numDataCodewords',
    'numEccBlocks',
    'numRawDataModules',
    'parseColor',
    'parsePathData',
    'parsePayload',
    'parseablePayloadTypes',
    'penaltyScore',
    'planBits',
    'planBitsWith',
    'planSegments',
    'planSegmentsWith',
    'polyEval',
    'pow',
    'printSize',
    'qr',
    'qrModel',
    'quadrilateralToQuadrilateral',
    'rasterize',
    'rasterizeScene',
    'readCompactAt',
    'readFormatInfo',
    'readMicroAt',
    'readMicroFormat',
    'readRmqrAt',
    'readRmqrFormat',
    'readStructuredHeader',
    'registerKanjiTable',
    'registerPayloadParser',
    'registerPayloadType',
    'registerValidationRule',
    'registeredRules',
    'renderSvg',
    'resolvePaint',
    'rmqrFormatBits',
    'rmqrMask',
    'rmqrModel',
    'rmqrVersionOf',
    'roundedRect',
    'sampleGrid',
    'scan',
    'scanAll',
    'scanAllPixels',
    'scanAsync',
    'scanPixels',
    'sceneToSvg',
    'segmentBits',
    'serializePayload',
    'shiftJisToKanjiBits',
    'sizeForVersion',
    'structuredParity',
    'styleSafety',
    'superellipsePath',
    'toPixels',
    'toPixelsAsync',
    'toPng',
    'toTerminal',
    'totalBits',
    'touchesFinder',
    'transformPoint',
    'tryScan',
    'unescapeMeCard',
    'unescapeVCard',
    'unescapeWifi',
    'unfoldLines',
    'unregisterPayloadType',
    'unregisterValidationRule',
    'val',
    'validate',
    'versionBits',
    'worstContrast',
    'writeSegments',
    'zlibDeflate',
  ],
  'teiqr/core': [
    'ALPHANUMERIC_CHARSET',
    'BitWriter',
    'ECC_ORDER',
    'ECC_RECOVERY',
    'ECI',
    'EMPTY_BITS',
    'MASK_FUNCTIONS',
    'MAX_ECI',
    'MAX_SYMBOLS',
    'MAX_VERSION',
    'MICRO_LEVELS',
    'MICRO_MASK_FUNCTIONS',
    'MICRO_VERSIONS',
    'MIN_VERSION',
    'MODULE',
    'QrCapacityError',
    'RMQR_SPECS',
    'RMQR_VERSIONS',
    'alignmentPatternPositions',
    'bitAt',
    'blockLayout',
    'buildMatrix',
    'buildSegments',
    'byteCapacity',
    'capacityBits',
    'computeDivisor',
    'computeRemainder',
    'countBits',
    'dataModuleSequence',
    'div',
    'eccCodewordsPerBlock',
    'eciDesignator',
    'eciWidth',
    'encode',
    'encodeMicro',
    'encodeRmqr',
    'encodeStructured',
    'formatBits',
    'functionPatternKinds',
    'getKanjiTable',
    'inv',
    'isAlphanumeric',
    'isCountlessMode',
    'isKanjiAvailable',
    'isNumeric',
    'makeAlphanumericSegment',
    'makeByteSegment',
    'makeEciSegment',
    'makeKanjiSegment',
    'makeNumericSegment',
    'makeSegments',
    'microDataBits',
    'microFormatBits',
    'microModeBits',
    'microModel',
    'microSize',
    'microVersionOf',
    'modeIndicator',
    'mul',
    'numDataCodewords',
    'numEccBlocks',
    'numRawDataModules',
    'penaltyScore',
    'planBits',
    'planBitsWith',
    'planSegments',
    'planSegmentsWith',
    'polyEval',
    'pow',
    'qrModel',
    'readStructuredHeader',
    'registerKanjiTable',
    'rmqrFormatBits',
    'rmqrMask',
    'rmqrModel',
    'rmqrVersionOf',
    'segmentBits',
    'shiftJisToKanjiBits',
    'sizeForVersion',
    'structuredParity',
    'totalBits',
    'versionBits',
    'writeSegments',
  ],
  'teiqr/render': [
    'CONNECTED_SHAPES',
    'DEFAULT_FRAME',
    'DEFAULT_STYLE',
    'EYE_BALL_SAFETY',
    'EYE_FRAME_SAFETY',
    'LABEL_HEIGHT',
    'MODULE_SHAPE_SAFETY',
    'SAFETY_EVIDENCE',
    'SAFETY_NOTE',
    'bodyPath',
    'buildScene',
    'circlePath',
    'escapeAttr',
    'eyeBallPath',
    'eyeFramePath',
    'eyeOrigins',
    'hashString',
    'logoGeometry',
    'renderSvg',
    'resolvePaint',
    'roundedRect',
    'sceneToSvg',
    'styleSafety',
    'superellipsePath',
    'touchesFinder',
  ],
  'teiqr/validate': [
    'BUILTIN_RULES',
    'COMFORTABLE_CONTRAST',
    'LOGO_BUDGET_WARN',
    'MIN_CONTRAST',
    'contrastRatio',
    'coverageReport',
    'fillColors',
    'isInverted',
    'luminance',
    'parseColor',
    'printSize',
    'registerValidationRule',
    'registeredRules',
    'unregisterValidationRule',
    'validate',
    'worstContrast',
  ],
  'teiqr/payload': [
    'GROUP_LABEL',
    'PAYLOAD_GROUPS',
    'PAYLOAD_TYPES',
    'escapeMeCard',
    'escapeVCard',
    'escapeWifi',
    'getPayloadType',
    'isPayloadComplete',
    'normalizePhone',
    'normalizeUrl',
    'parsePayload',
    'parseablePayloadTypes',
    'registerPayloadParser',
    'registerPayloadType',
    'serializePayload',
    'unescapeMeCard',
    'unescapeVCard',
    'unescapeWifi',
    'unfoldLines',
    'unregisterPayloadType',
    'val',
  ],
  'teiqr/export': [
    'EXPORT_FORMATS',
    'ascii85',
    'crc32',
    'createZip',
    'embedImages',
    'escapeCsvValue',
    'exportFilename',
    'exportQr',
    'getFormat',
    'groundUnderLogo',
    'packImage',
    'parseCsv',
    'planBatch',
    'sanitizeFilename',
    'sceneToEps',
    'sceneToPdf',
    'sniffDelimiter',
    'toCsv',
    'uniqueFilenames',
  ],
  'teiqr/raster': [
    'Raster',
    'adler32',
    'crc32',
    'decodePng',
    'deflateRaw',
    'encodePng',
    'inflateZlib',
    'makePaint',
    'parsePathData',
    'rasterize',
    'rasterizeScene',
    'toPng',
    'zlibDeflate',
  ],
  'teiqr/verify': [
    'NotFoundError',
    'UncorrectableError',
    'binarize',
    'correct',
    'decodeLocation',
    'decodeMatrix',
    'decodeMicroMatrix',
    'decodeRmqrMatrix',
    'findFinders',
    'groupFinders',
    'joinStructured',
    'locateSymbols',
    'quadrilateralToQuadrilateral',
    'readCompactAt',
    'readFormatInfo',
    'readMicroAt',
    'readMicroFormat',
    'readRmqrAt',
    'readRmqrFormat',
    'sampleGrid',
    'scan',
    'scanAll',
    'scanAllPixels',
    'scanAsync',
    'scanPixels',
    'toPixels',
    'toPixelsAsync',
    'transformPoint',
    'tryScan',
  ],
  'teiqr/terminal': ['toTerminal'],
  'teiqr/kanji': ['kanjiTableSize'],
};

const MODULES: Record<string, object> = {
  teiqr: index,
  'teiqr/core': core,
  'teiqr/render': render,
  'teiqr/validate': validate,
  'teiqr/payload': payload,
  'teiqr/export': exportEntry,
  'teiqr/raster': raster,
  'teiqr/verify': verify,
  'teiqr/terminal': terminal,
  'teiqr/kanji': kanji,
};

describe('the public API surface', () => {
  for (const [name, expected] of Object.entries(SURFACE)) {
    it(`${name} exports exactly what it is meant to`, () => {
      expect(Object.keys(MODULES[name]).sort()).toEqual([...expected].sort());
    });
  }

  it('covers every entry point the package declares', () => {
    // A new subpath in package.json without a snapshot here would be an
    // unreviewed public surface, which is the whole thing this guards against.
    expect(Object.keys(SURFACE).sort()).toEqual(Object.keys(MODULES).sort());
  });

  it('never exposes two different things under one name', () => {
    // Same name in two entry points is fine when it is the same export -
    // crc32 really is shared by teiqr/raster and teiqr/export. Two *different*
    // things under one name is a trap, so compare identities rather than names.
    const seen = new Map<string, unknown>();
    const clashes: string[] = [];
    for (const [name, mod] of Object.entries(MODULES)) {
      if (name === 'teiqr') continue; // the root re-exports everything by design
      for (const [key, value] of Object.entries(mod)) {
        if (seen.has(key) && seen.get(key) !== value) clashes.push(`${key} (${name})`);
        else seen.set(key, value);
      }
    }
    expect(clashes).toEqual([]);
  });
});
