/**
 * Shift-JIS table for Kanji mode.
 *
 * Importing this module registers the table with the core encoder as a side
 * effect. Once registered, `encode(text, { kanji: true })` will use Kanji mode
 * wherever it produces a smaller symbol — 13 bits per character against 24 for
 * the same character as UTF-8 bytes, a 46% saving on Japanese text.
 *
 * ```ts
 * import { encode } from 'teiqr/core';
 * import 'teiqr/kanji';
 *
 * encode('こんにちは世界', { kanji: true }); // version 1 instead of version 2
 * ```
 *
 * ### Why this is a separate entry point
 * The table is 23520 characters of Shift-JIS, and shipping it in the core entry
 * would add ~10 kB gzipped to every bundle to serve the small fraction of
 * users encoding Japanese. Keeping it opt-in means the core stays small and
 * nobody pays for what they do not use.
 *
 * ### How it is stored
 * Sorted by Shift-JIS value and split into two varint streams — the Shift-JIS
 * deltas (almost all 1) and zigzag code-point deltas — then base64'd. Two
 * separate streams rather than interleaved pairs because it lets the
 * compressor model each one independently, which measured 10,342 B gzipped
 * against 13,620 B interleaved and 19,183 B for the obvious encoding. The
 * table is decoded lazily on first use, so importing this module costs
 * nothing until a Kanji symbol is actually encoded.
 */

import { registerKanjiTable } from './core/kanji-registry.js';

/** Base64 of: varint count, then the Shift-JIS delta stream, then the code-point delta stream. */
const PACKED =
  'qTbAggIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQwBAQEBAQEBCQEBAQEBAQwBAQEBAQEBAQEBAQEBAQgBAQEBAQEB' +
  'BVMBAQEBAQEBAQEIAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQgBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFPAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAWoBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBARABAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQ4BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBggUBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBCQIBAQEBAQEBAQEBAQEBAQEE' +
  'AQQBhgIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEtAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQHEgAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQFEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAUQB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBRAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEB' +
  'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAYDAAQIClLwGBKW4Br64' +
  'BgIIO8u5BgLPvwGY+gev+ges+gfKAscCg7kGAsEBArUCtHuvewIC6gPNQwn++wZaRPH0Bu70Buv8BgEZAgYC1vsGAum7BgLMvAYE' +
  'PASpvQYCAgICAgICAgL0uwYEt/kHTEDM+Af58gb48gYE7/IGApEBLJwQA5+WAYR+AqADxPsGwQO4AwK3AwMGCCzx+Qe+lQEBcwgB' +
  'DQFJASYBFgGBFq4//zkDAgSAOpU4BvYBAgkCsQEBAwL09gaf+AYEWAY6igLaAZ8ECrQBHTACoQFGPzATAoEE9QP+GAMFkxkC1X3y' +
  'lAHC5AYCAgICAgICAgIQAgICAgICAgICAgICAgICAgICAgICAgICAg4CAgICAgICAgICAgICAgICAgICAgICAgICsbwGAgICAgIC' +
  'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC' +
  'AhwCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC' +
  'AgICAgICAgICAgICybUBAgICAgICAgICAgICAgICAgQCAgICAgIQAgICAgICAgICAgICAgICAgQCAgICAgKOAQICAgICJyoCAgIC' +
  'AgICAgICAgICAgICAgICAgICAgICAgICAgICODUCAgICAgICAgICAgICAgICAgICAgICAgIC4oIBBBQIEAcQIA8gEHUEGAgQBxgg' +
  'DyAgVR4NHhBDJhUmFMMDAgICAgICAgICAgICAgICAgICAqUMAgICAgICAgICwEdpHFZpHkdmNgyTATIFED4dwgECAh8CakVLuw0E' +
  'kTzuStdKhkYCAgIC7QECDooFAQGbRTkcwAK6rwH0GdoT+PAB/YUCtjGaCOMk2NgB2S6xBZcjy2buDIgp7yDyef8GnmXDzQHXRfQ5' +
  '3wyrG5UH1rIB8kmjbrgBoHfv5QGSarAw27QB2AyoEZwO4gb+tQGMB/vAAdNhSoYBoAHYAtIaigm6AlqQCKwTYMIBxhLkC+oeqhJC' +
  'lhLkDoQBqAuWDaoRvgqmFUr99AHLEiD0JKajAZ5Ao1/dqwHiK+JWrIYBi1jsI7kCyGbbqwLeCJoFSP4Htgy0FLrnAY2sAfJLkhHq' +
  'RBxgtgXfjwIvqB6QVdw7ikDMHPGNAtqnAsOKAdGyAYSqAdIlq0+bYKcEslj6Z8Jcq4kC9xj6Zuwd5oIBmf0B4R70hgLOGsVO+lbV' +
  'lAKqB/QVghHeGqYDogToEPYCbOQc2gmMDsx3hVXUFYoImiL1lAHyH74E9osBveQBtqkBkgrQIMewAcFXzQiYFrwEqATgCYQN5ASC' +
  'DpYBliOqCfQFjAKKAfgB1AWEK+oRtgGMC5Ir9geAK+OSAqY1vBqWI9eMAeocbrYYuAHAC/wM4BD6A5oCrh/sMKomrE877AbFiALq' +
  'P8pb7ckBji3WFaCAAZ9l1iePkAHCBvwN4jOAN8wwyHbPpwKWFM8QzgEvyAFb2gyeBbQIjAzkBuoDVuB3k02qBDSsDs4F8A6uDZYX' +
  'YvwBlgXUHFRS5gHwATemDpgNkdIB/tkB/AzQAaAbp0KL2wHINNIUkEHEC9QysAOCEYQXiiicCYQDk6wCngGS6wGJzAHYBYAC4hjg' +
  'A37UAWPcBYQB/ALSCZDYAbXTAZQJjhPyC7gT9ATeG+AUqBWkNoYE4SfX6gGaA7AZxRGAHMYFpBG0INoQvCv8MJgOtgjqJKIcl7UB' +
  '+LABnUvrvAG4QZ57gC2V/gGIEIUKniucELAHhg4Hhg7uHpAV4gbePHCyDrAG1AfsEuIDqgOF8AGaBZQzoLsBAuXSAYpe6UOoAZEH' +
  'rs0B27IB2XPWDKYr+AmeKZgDlAOUVuoS6BjfhALKuAKFoQLKVL4ElLUBs70Bm1vOpQHeJ9Q04Abh9AGamwKL1AHGa9gElx65qgH6' +
  'wgG9N8+ZAYoEugjkKI8nnAMeqCzBIaAK+AbMBhiGAa4KDtQI+AGIAbYBugiOBt4JhALOAogJKogElgvqAaMB1hXQAZYHUOgPxAKA' +
  'ApAHmgX0AtoCkgfwBKoYsgS+B7IPmg+EBQMihgPcBaoFn1y/zwHmF5oiqAS6V8YK4AOlaoSNAcA07CagBYYBCK2lAhrGEdYImAOk' +
  'BpoFhAf2ApgD+AXkAZwFxBCYDcUFFvoE2AYNtgbdMKo2pAHMAYQkkg/Jd7p6gAyFdaSnAZICuAqGA6oFogGKJ9gE3AT3sgL6B4YC' +
  'piKSCKYaogHYCZwZzB3iC+wOxBmkIYIL6AKHnwG8gAGsT62OAgvQBtJKiAiwgAGRSeNCsN0Bsa0C3CDwlQHsFOwm24cCWoQClAHy' +
  'EtwB7B3KDaQE2BTYB4oUYOIBqg6WDuYZcLQBpAg30AH9Xegxv3qUIsYG1BMcco4s9GCuD9gOthTtjwHKKuiGAeOyAgYC3gMK4gTs' +
  'Ad6mAYmmAYoCvAVlvAHYAYIHrgu8EawJJsoDQjrkCvQI5BPsCYIYVoQUkiQahgSMDdIu1Au8ELAFhgTTrQLaC6ApqCnYC9k05CqG' +
  'Cqgo8SziUPeuAb4IxhHuGtDUAYO2Af4VNO4jmhV4nAb+Cd4TpgTmEsADtAewEoAI4/YBwvkBxZACsgfeDtUCun7+AqYR+iuSL64s' +
  'BBS1oQLGPoiVAdvCAZSTAYeoAbot6NEB/BiloQLScpicAavWARGgHY5clzjCqwGlIO1SvyT8kwGLaNVRslm9WLasAfOBAtIEoMYB' +
  '0BHdKdI8qAj19QHE1AGNPf2lAfgDpgWZA54QtAf6cr1xjAeiGETiA4IEHYQBkgiQAuQEhgSmB6IXph2uE/wKogGaAeQCwATGDniG' +
  'DvYMtgGGBK4OuiTqFa1rrDS0MMGlArA+yAn6LLKbAa+5Ad9enmq0BbQLwCy4C+Arxge1jAGjYIYFJX6uBPgCVogN0AXsA44L3BDw' +
  'CowB9gP+AdQWmgSoIV6EAswTtgGUFNkZuibEI5wGkgfgB6IGpAyKDLYH/AbKEem0ArgJKJAr1gLqO+oB6BP0AYol6BOSH/QDrC2D' +
  'oAL6BrIPsAL8Ca4LpgaaCvQC+AGiDJoM1AnOGvQR9CfUL6UggAGeDLwJ8hDCDZ4RoBLABtga/cECA/YB9hCCBBXiF7oVKvwDkCDO' +
  'B5gnzhC6SAymA7IY44wC1rUCybQCsANm1AEF5gRG5gQ0igG4ApIBXAX2BZAHogG2B64HEmSsCQQgggIWLjrCAfQE9AOWBYIBngOo' +
  'Bo4DggHiAvIB6ALsAegEqAqWA36MA9wBqhqqBcoHpgfCCkomjAGmAcgJI9gCBMYCdrYC0AT0Eyr0Co4GtAGcD9YC+APjaPpq0ArS' +
  'AvAGqAb+BMYJv6sCoAGYBSKaE8Qo0jOUcuoLtD3btQLgA54I5gqGjQHuXNIv5AWbrgH1EM5JvTGnVLoDnOcBmZ8BwnOvkQG+sgHx' +
  'pALMIOgBtAW4BpwYvgWQERHmCPABjBW8H8od6BSoY82yAuoC8hH6BNIh7gEQmii8ErQfng6cSYwl7SqdxgGuHYgS60kRwgPmVe1I' +
  'qg66BeoH8g7IC6gFuBLsDKoK6gmUhQGNfaoWIo4FvU/EXtgayhOQGaQe7ZACiBPQQLRg7jTZ6wGcFtD7Ad/3AaBF1FyDsAG4IaMU' +
  'soIBypUBu7oC3AuCCeY+1AfYA8IDnkqkA5gHmlilqwGizQHngQG/oAGdBtoC0CauHPAGcI4JmhLeZ9BEgYEBjJUBk+IB9L4ByiLX' +
  'kwHZQZFhngrUDN4i7hHUDqID+AuOJsgHsgXoGdYLpiDcE7AFuhKwHsfNAf4DwBPrcgHMAYoB9gr8BgviB/ADoAjAAwNsogX6A+oG' +
  'UtgGjAHUC9AIpSemKRxW6gaKDzKoAuwciBjwAe4MQiTuDcAB4gPGHpADFgVMxAGyByrgJ+AImbYBx3PiAqIBhgeOKMYCnBXyBoIN' +
  'vhPUDp8Ihhb+Ca4E2gvyAaQbTu4G1AqULJuNAd7IAd/9AZKxAaZH4YgB/E/VzQG87QHPowLcF4wQ9ASwBrYDyhPsN44C8BrYXJXF' +
  'AcKlAb8k260BhF7SaveYAdKjAdcc4A/pwQHWKcgd/KcBk58BpC+gH7IP3AuwLNoOyAbNJsYnlYICtguAJbIs0iTyBq58+AHGBYtB' +
  'xZwB3g2QB/tKthbkHoYbzBOyEb4d7gOcGfoc8DDeDoghh6ICigumAqoekh7iGuZNqGXLgAKXDLQC3hy0AtoG3zemRPoH6CicMhbu' +
  'DZYEiga2CGTiCewO2AS8CMgL9gKEBLQEQrQV0xS3iwKeAuwH+AekMfYJjBfaEZQHsBWGK85O7ALd+gGKFcwKpEiYLqITpQa5kAHC' +
  'ZMl+stkBuh7LgALiNNQkjkbuDPIcxl/xoALIN4QZhg60CNQJxgKcA7QerBjlfKjKAaQE/hm/mAJuxkCiEZABgh3HPbh8wAbzYe56' +
  'kAGCFJ3hAeAEtBa4FIIEigOeygGADtmWAtAB/AaGAU7KAvgDvAEpzAOiDawB/AHyBaIBEgQS1AkMrAGgAp4MCq4B4gIpoAoKQpIB' +
  'kATIBPoFLI4KmAOCAp4ByAsrggHAEfQEuAXIAsgBlgLgA2KsBqQCug2ADeoC/AKoDKwC2AQ6MD7cB/oBjBOEA7AEtAKICvgDm6YC' +
  'AyxygA2yA7wVzAGwAqwJrAyaCvIQxgkV3BfkFfoK4BOqKfQajBnQBd3zAYYHlIQCodgBwBiSCq4ZzjHGCPYH6B3yO5NGuCHrzQGF' +
  'NNICV6QVshT6Bhi0D5YGwgeCCrYCxgraAroP8gGEHYwCzAX+CJACmg3gEpgD9guAEKAC4hHgA64C1gbUFJmhAg6EDeQZ7gG+DJ5k' +
  'uWOilAH4IvYWvBqUBI9x1D7yNMsa3ekBlQ3e8QG77wGSDcYahhaYIqwRrhvUFKoNoCKkH6QE+AYQ7g3hiAHMmQH59gHEAY4g5AiM' +
  'mAHmJNnNAbYPoAfYaqRRrQWDN/NlkyyDIsM3rIgB4hTbPNVR5AHYAuIb3BbMAtIH3gxq1gKqAfwJtwOaDcQK2hHaCvgGxhewDsud' +
  'AZrAAYQCwgQZcKQV6gWAFw6fxwGKUvAb6lab4gHeCvwElg7eAfgFxkG0CYAI4geYC8Qu8AL6AfwB61bDmgGkQ5gDugLTBqqeAdM+' +
  '+gTYO/ww52WsEvoU3+EB3gn2BzqGIb4BKI4HkhFC0gnGDUKqEvgBW4cVkh7kB17jLuhS3ATaCOABvAWkB8ICPNoNkBPACc4EhgoB' +
  '7Ag35AvWGMGlAu4M6Gb8B5t/uqABoBO8DckTg5oBigiuEYQcqA0Bugn+JewKAYAOkAGSAvAKkgJIhiPaEI4wsxf+OvG4ApwGrgUs' +
  'sQ/CFogNwgHcY+NasgONJYw3INIJTocB+AGkBLgEoASrJNQvYLAUoAu3jQHAnQGeBLYOmAngA2WKC9ALHqgEoAH+BJQL1hKiCtgB' +
  '1AyKDuwLhaUCkB/uI4qBAcQNph+wDLmBAuICpgfYBPgztAusEJobjn7YCY+BAo4y2MEB9ZsBll+PqQGI1QG/3AGaSdUhJr4ChiCI' +
  'DZakAYuGAogpIIxNwnel1AGuC6AGlh3GBdwV6Gm/Y9azAYgOyAGpqwLmIvAPpJABvY0B/AWsBbYC1gTSA5YT4hfcB+BH4gKqBe4W' +
  '2hCQDVy4GaIh/wvvswKaFO4UiogBwln+GtoWt7wBlAWnc+IHghmmG4wBap4nmg3mEOpXwijtkQH6bIsfocUBotQBm8wBAcUSnIQC' +
  'xwKL2QGOnwHnjAHac6pTyZsBuo0B/WSgpQGVyAHmgQHt8QG+FNwKwAW+LboDiAnQFaYK9AGkCYAdhAz2AqIIhAqSAooYlA+MI+/x' +
  'AcgH7hneGdID1A/qBIQmoFbF6gGCnwHpggHWH5QFqhjMF6gmzBCoFYwKyBTaJNwl03fZGboWsAHmJZgtzVjSAsgiqaEBvnGlpAGK' +
  'A84yjhG6C/4N6gbuE4ZmmAiIB6Ycyga6G/G+AZ4YiAz6PuAFsCHb+gGKDYoCgA/UGcIIOpwBpgJCbJIB/Ai+BKIO9gGiIcgL0AuA' +
  'CPQkigN+/BeSDTrSCtwBzhK6C5YKxhO/qAKkQrpOvT/mFYod7GPWG4oLm6UBkVLkQfwC4pgBug79dv5o/94B0D6bEY4Z72rSf6cd' +
  'xp8BqSrjHcBWqagB4hiLYJoG6giAiAGDLL94svcBoi+NvALCApwEMpwHtukBq+EBuA/sDYYK8AEwlAFQ2gXSCIoCrAK+E6IOjjGO' +
  'BPoBqg/OEfYeyAO8DZ4HygLqAdYC7DTRyAGZIpQCpgL+JaAerhKcVdANrZQBj2eOK9YT0qoBwAKuCZeDAuYb/ALYDIQJyD2oQuUl' +
  'wF7MCPIlw54Bt4YBxHLkD/4VlocB2ZYChAvKEESqBegK5AyKGIoHihu0Icg1nCTODNIDoAnPbCqflgH4L40eqgm8Gv8/kAWkAUJm' +
  'oAyIDQj+A/wIwgWqAuIMsgewBogNpAPyAUbwN/0jrgKnA6gLsgXpSYpavg6kBxYDiAa2AoGtAebIAYwE9gHUEOwDhAWSB+gHGJQQ' +
  'ugnuBoYIrxGVlAKQCO4E7A+YELIW7guAIqoq5AyeGKAMnjHkCMnWAc6AAo+nArAxONI3uhPUE7gJygijQLQcgl/TigG8CdFhkqIB' +
  'mUXTM9iCApVoy5wBiNYB1YQBy2buF7ARvhLMHJx/zg+kH4OPAuxJjK0BieMBtt0Bu/wB7wy6Dt7OAeoV62q7M6K/AdGnAaTBAd9u' +
  'mSK/iAGSWP6VAYggi6oBoXfgNqgLssMBzfMBnucBjzHgF/OdAcwb413kC7og+gre7gHlowKeKoYZgKsB12qeJ5sB9XWUogGLRfMF' +
  '+UyCBowOvgTSNKorqbkB8kLhQqIm8wSOKLQ8lDXgD2yYAuY3tRjlC9+iAawSxgi0kwGfiAHWFbgB8Bv8D9t33pQB8Az+W/GmAqA7' +
  'tBDqAooHsAioPe0RgDoj3jnICP+EAtgfsgrmN9wD4h+yBvRmic8B3M8BlCahGbMitTb5B4Qx89MB7AzqA+Y9hBT2E+YmrhSCBMIW' +
  'nA3OKZukAYYhzAuqMKAWrFjKE9GyAuimAf0MjA2eE/0Uv0GNMtaIAfUsHumPAe6DAquPAdwfumymJbOvAsDBAadz5mKsaYgd3ZkC' +
  'vgeWugGwP4+eAuALzASGAhzWKMwYygXcB/4SIPQXzgH8BM4F2iPWD/oOgBvJQ4RYuYEB0poBugPj1gHYDII89AXYB+Yx1gaHzwFO' +
  'qgO6FYgU6gPsBK4GYGTKC4gZ8APMI/gDxgeOBeYP2AbcBIwgnAiECIgPvhv6BZ+7AdpIva4Byi7gDbIfohG6IagLiiLafuHdAZpJ' +
  'u5sBpIkBxJUBje4B7ogBqAmxDbeFAZICulbIF+xTqZ8B9zngAuqJAaMa3FLt7AHqPd4qvAiWC8AXjBKAPNoHyAiztgHgE+xHmhCK' +
  'JKJBa6s5ogmAVdedAtYqwBigH/IKpHJY0C3XywHOPtGbAZYDkCSWBfYEzAXHKLYxsgL0BcAJggxgjgOAHJAT4CPUGJQB/gOGI4gF' +
  'jAGcAtAiUKuaAvpT9hrwWoYJkgT8Lc3TAaQ1qr0B21C6A4/ZAcAN9DTHBZAjhErUH5we/gGhbrs7/AzGKdF3tI4B0qQBl6YC6gjy' +
  'CP4I4iOUA9g61162jAGqAXqqZ9HFAa5rickBuAWACJYbxhggrgL0IrtmrtwBmEGkA89nnG6LnAKMH6p2ogmDmgGAlgHYNZUm7awB' +
  '9CL8ZIAmwgikRzTyAZuCApQMwB2wE9jiAZ+fAvTIAaZDze8BpDGoIIQn4k7wGKNTxZ0B6BaEI+oCyBK+FORB1B6LzwFVmgyCBdYP' +
  'sASoCaYFAXTaBbYQ7AKuB/YBpAWUFxiwEPIc8hfmCqoHsgXAA6wIoAiwBMAIuBHYCNYY7A/yAbm8AqQB2AeSB+gTvAmqErYGAswJ' +
  '6hHOAeoChAT/XJ6uAZIO/AOwJZgGZv4W6A6jiAKYkAKplAKDCY4KmBWUMIQK5iz+E8ALwF7F/AG8Z7UEi06YGe8TsDeeY7O4AcqT' +
  'AblJ/lHYiQHODd+bAtwH3DHmBegQyVvgU4cujo0BjWiq0AHXzgGo0QHpzwHtZvoEyg/iO+QRgBayjAGtgAKAuwGkgQHvwgK2Tbw0' +
  '1gLQV7/CAe5KttABo/UBxHbRe8sDrK0Bo2OOWvkq6BvdnQHoiwH3QZ4sjZEBkhn+X/wE+BWYffQYq9EBlzrNAeUh0AngAaJGokOw' +
  'ZMIKuCmTjALmYa8O73X4XexTWuxlsB2D6QHSFsJj+6UBtgf4QYAdrg+AG8oJhBLNzQHsV+LeAdWfAZc+xVGMmALB8wGuGIZp5EDB' +
  '3QHOLapx6mH9iQLDEq4NzB28ZPg3sEbRygH6YruRAeovlnbQIo4StBGSI8W9AfZ2yjqTzQEB4i6yJrZSlhGR6AG7F7IHugaIBLQf' +
  'sAvGCMQDqAnmDKIDmhq1A9QWAvQHvhCKPoYH5BaOAcgBnhftPO+5AZkqogOVBfbxAewSoiPFnQKeN8sTxgj+C8QUQI4DtgjcCZwC' +
  '5gzWBrwLqA6OFrYT7AGSEYAC8BLABtILtgmwGJoKl94BpgTCIqIF4gOwSWD3SIpH6iD8BKWGAZhxllKJBbenAYxBuBvaNPGLAogU' +
  'tifoNs4TxFfAAfQN+90BzAesIdIrtAW8LfoBvgXaSyTWI6wU0wHZ2wH4T4gdhibbggGKR7eLAfBqtgXaFaAFpAzOEOhn027ikgGt' +
  'vwLwRq4RroIBq98BUNgI8QrWDsQo1ibQC/YUxhXGDNYF3gmWC5AWxiHUFqYFzBLGBvmVAuysAcu2AdoN/k/oGIoQxgnqNoQ18h3o' +
  'FpAJ/agBvXCwVaw+3mzzpQKkAaoB2Aj0A5IsxAmsTpQWribCPYYSfiiaHpYD9+IBnBO5ZZgCynj0X/GnAYQGigWmNswI6ivsBvYJ' +
  '/hHqLJIM0/sB2pwCt8IB7BbycNoEhiX7kQKaHpISdKYgygkwrA/KBqYNtALiI6gQ+gGaG4Ymwf0BzLQCnZQBjhzOSrch0eoBvhHK' +
  '1wGNfLSFAfku64ABnhuk2QGxvQIB8LUCyUbTErEBz3H8FbIo/CKRiQH3QwoqDgoMBgYoBFQGzPcBwfcBkM4BiYwB/UEgAgIEHAYG' +
  'MAERBAcqDh4bMCSiAVNWBAsfXiQOEjkjDkJDLiCEBocFFiEUBhMSEygCahwnLAk/0QO0A1YQBlsdRBV6CPha21oJDyQHLBgQNCle' +
  'Ay4CLR4oEA4QExYWBygPAigBAQwOMgUKAQgCJAsQHKymAZ2mAQIIJASsFZcVBQwEBAQCHAQHDgICEAMCAwoQEAgkCurRAdfRAQgG' +
  'ChIMDhILMgYICgwsFQ4CJBMsFBUUGAMgDgNBLhKu9AEB9fMBAh4NGBgUDgoGjpgCmZgCJgQGAhoE4IgB1YgBBgEMChIYBAQKEAwB' +
  '2xTkFAjtBZAGFgrUFrkWBxYoFAwBEgQMGp6hAY5r84sCukzkK/93CwoaDngGJwIeGxAZF2KCATMyXSQMDUQtChMcGBOCAUksJQ4w' +
  'CD8GLjs0AzgaAlIKLR0BGi+uAQ5GLTtcLSICPQlUeDGhA7YDKkcGNAwgYw5MQ0JkKTQ1MBAfgAE5Pi8BPEOqAQSebtVuBAcMZg1p' +
  'egM4CxQsFwksEhADHAsKBAUQDAYECC4WDgEKCgEGBAwKA50FqgUUIgIsJQoeNK4Bb008FBQaJh0MDCYGHAMCbmcaUBwIqgGhAYIB' +
  'LUqgTdtNKXgYaDMYHkhFBRMuHAMMBAEaERAJIBYBBAICChAMFpY+gT4OAgoMDKiGAfmFAQkDGAMUAw4KBR4SOP0omgHwJx4oRBed' +
  'AZgBApYBCxsWJSJMWEUnAlgQYEQEGhEJTBceBiVIAiIBFjjDAbQBGBAKBAkiCAoCFAgOBgQGoCibKAwGRiQWCAQWBygEBwcODAoM' +
  'BSQEAgoMGgQMIAIQChAKBQG7A/YDBJc4qDgGJgoG8QugDCAJDAkcDRIkICgFGb4CwwJCFASKAXkHEwYcDwEBaAwHBUIOBiIFA0AJ' +
  'HgQeWU4KGggMAQgKIA4GLB4BDxQ2AhoBBRwSBRYGBDlcAgiEgQL5gAJCQgIMEAEOGgsFAg4BDgIGCgQFCAgMCgyoAQGhAQwKJggW' +
  'Eg4IBD1ECgIEEBgMCBgBBRYDEhMuCQEQEAoeNEotKA0nrAPnAkR+jQERMjVGKwssCS1WQDFSGi8pBw4sP0JDVAEjUBi0AccBLisu' +
  'CQIJKjesAVFQGT2HA5oDEiFG6gFvHR8CEhcMEjxLEzgCchErAUYVBR8QEgoEXgg9AgIiEgkTGCMDE0RIBR1KLwwfDjQGPAMBXF0J' +
  'Bhci3HbXdjIFJggLFgMBBAQQAggBEA4GBhIIBAQCHBogCg8KECgMDhUoAgZ8oQEihgELKyhgcZwIlwgoHwMPCldchgE7BmxJDDEM' +
  'tgEjHp4DmQOOAQ8bVmlaJwssLJMBA6oBVlEMOjMSSGOkATxbGiYgzgOLBCIxsAEQDk+4A6kCAyQIQWg8DxkEFzorXhPEdNF0AukI' +
  '7ggYemsDAxAMBTYILT4BEBICBAEEpkCFQBwBDxYMASoMFAKOmAHdlwEIGBgYBgkGEAwSAw4CIIIGzwUND/AF+wQCAy9mFQoPOgEO' +
  'BgIRBhwmCgwJCSgKSA8gFQMQFzwIDMECzgIGDgoEMA4QEAKiwAGTwAEiERYRAR4wBA0UAkoxclkjRAE2CTdkcHVwcWxhWAsBChhp' +
  'Kg9C6gr7CVA5Lho1OMoBjwJcFCgQQB88MRIDL9YI6QeJAYIBKTSqAYMCHYYCbXxflAEIiQFWfQ4mI8IBRxtZGIQBVzEecgQfEgO1' +
  'AeYCAzU4GS1UH2l2bThRYgUBSC2QAQdEIQQkKSDLN8Q3JkMQN44CuQIeBw0+VBQ0MjeWBKEEDRU8pwHaAWFOUT4Q3gK7Ah9ib8wB' +
  'd4QBYTYRGjsfK9wBBSY3PAIXgG63bRABEwkNZBkcaWAgIhSibLdsMAi2wAGjwAEyAcouxS7qtgHNtgEHDA4SCQ4IBC4CDAIIARQW' +
  'BRIMDAIIBgEECAoUChAYGgEQB57LAevKARYCDhIBdhEaEDAWGjE0OSsWPgNoWjsrNCMwXQYaB0IoKyJq3GytbBUkCT04A0ELrgFg' +
  'XRM+P2oOngm9CegBOBWpASQ+WxxMGyM4KxlqQRYdKgh+ggF/KbIBJUE1kAF/lgFRW0gRKFO2A8MDNpQBUCNiIzgrGyojRAKLASw6' +
  'RcQCX/YEvwUYDIIBmQF+gwGGAcsB5AFVN54CFwMSASEnsAKLAioLR2wGYrcBmgEfAwYqGjdqEy4vCDIFJVwEIS4fHCE6AcsC0gIJ' +
  'DiIcFz4kbA06hAGJARgJCWInJAdgFz4FmAEfZkMHKxQsRtgB7QEiJghWOwooERYLJBgJHA4FDBwGFhoKAQgEEgIGAgwKGjgUCAEM' +
  'FggYCiQNIgYDFAggAwIwA8+LAZCMARkkCw4uCQsHMiACkq4Bga4BJgMQEAUMAZwBKTYlCkoSH4gDuQLUAZMBWXQQNitACy82Gg4Z' +
  'DhgQGiYSRgoKxQPeAwYIBAoIAwIOARoBBA4EARADFhAMIBASBQEkKSgeCQYIBBYDIAIlLAENJAwGEAM+HSAbEAkIFTgFEA4UCUAC' +
  'BQohFA8CMAQHLBANAgIEIAcWGAIDLAcSAgwCAgUKCAQIBAgIBgoGBhAFDAIsCAgCAhAWEgcYBggEBoo95zwaAQVKCQsOAhU4Ah4m' +
  'HAYfFDQBCSoFDB4DJAwGDAUCAxgMFAYEDhYcIAyoBIsElATJA5IBMyQTPBsuJBUKRBUKEisDEgpECRlGESYWARAmASpAERAJCQNO' +
  'ChYmFMiWAcGWAQgKDAIeGCQKFQRKChYCDgG9AuICFAYNGCgbMAIO6JQB2ZQBEggWHgMGAyY+LwweAQmIV/dWBgYEDAMMAgYIAggO' +
  'BiQaCQdaNQIKLhkcNFTrAZIBgwGCAQ1gHx4ZEgIJBF4JDiMeAx0OBWN4ZBMWBjUkLhhQBlsB9gG/AQ4YPwhAEy1aCAYVMBckHhEi' +
  'CR0gEA4KGx4OEhwaKBIVEhMOFgEBBRYIBgoFLAsUDLJ5l3kGBAQIGAc0DRV2DDkIGhMiWjkPSBMMPShgE1toIzw+FxUkJBMjpAK1' +
  'AhpaRzEiUAoOCzoRIUgKMgMdPiMrBC5IQFULCBQXCRBaEw0QCQI+HQEmARDbAtAC4kTdRBICBgwDBgIEDxoCuAIEFg4CAgQCCAEI' +
  'DgIQAgMiFAgFCgEKEBQBBRIYBg4VEATyLtcuAggWARoKBhQMxmOrYwMODgwCBgoOLgceBxgMBAoGDBYBAwwGCAQKBAEsDw4mubwB' +
  'uLwBXhQXCDEsB2YzBFQcCxg4gFWJVQ8qA6kB6gEFEQIcHgoEEwQ8FR4BhwFoLA4KEgsKBgQPHggIEAEfJAoCDiYCBgYCBgQGBgYM' +
  'JgQaCRoyAQoFCgoDDAQCeYYBDAIMHgoyFzgdagQHGUQBDrICnwIPAzVQU1pfuAEBOzgBHg0uFSsHJwLaASogFQYX5QHWAQ0GG3KD' +
  'AQRWLT6YAT5POV4MVWaTAWwgTSQ2KgPFAfYBnAOVBOQBhQEkvASrAxkXhAF9KDFFM4YBFIcBqgLPAa4BDD90FyM+Ex0KIGmAAkMV' +
  'RgIoGRMBL4gBRhUfDYID7QIUVkg3Eg08dU4OngHFASpJDiRyHSorLgoQEBE6IhIPGQcYOA8sHhzv3wH+3wEWEBREIAwCPQJUDSoE' +
  'KzK0Be8FUhQWBhkHKEYXBA8GDywPCCciVBYPCCsIHYwBATJXBEw5IgwpCyAOtgLFAQU5WjgbBiCMPNU8MiEoARVoBiNeAx0PAi53' +
  'fgoBGgEgCgYjKBIDIA4KCBIsBUBREHCFASAqCTgpEikuGB4bJAIgCAIIOBILDxcUJBADEmBJDgoCLAYRCQQoXYYBAxADEgUKCgYO' +
  'CgoEEgoSEAUMBgYQBgQCNAQCFBoIFiYLBx4EECIWNBEXBGgdARNGBQRIDR8oAhcSQhIVMCIQFwUaRmcEKjEFYgkmcWoLDhIm8DGJ' +
  'MgomKzIWBgEJGgoBIhcaBgoSBhgECAIGBgLAAg4DEggEBAoaFBgEEA4HCgYCDC849akBoKoBBSYVAgkQJA1GARFGBQISAgoFEAMG' +
  '/Ej1SIsBjgEEogEMCAQcMFIHByoWBxMeHz4CFwgyGAITPAIbHkYZCQgsBQQGCA8iFgdrchtCBxQKDAMBDgESAwYKIhEWCCwpGg4G' +
  'BiAQMgEfJhgJIAUOCxIGBx00GhADGAUHHAUFEBIKDAICcAYIFAQQRhYFEAqwAqUCIhcCLggYJyIPFTgeAQiBAa4BAgIChwF2FTAE' +
  'DBQODuQY6xggCQgBFAEMMg4ECFoEt7oBproBTiAOMgM0GAQWBAgUATIDDUASCAkWAQwMAhAECgwSBAtCDQJQPSowLQeaAQ0jCDY3' +
  'mgGrARgKmAELBRCBAeoBKwNkTCmUASspEg8SLgkMQgg4Gy+0AQcCMUo6AiIFGSk0GQ84bAsBHwgSTBUUJzIOIhsuCgQHGIEJjgkK' +
  'BAxFRAQGA4YECgYUBAQCDhABDB4BAwoYp5cBmpcBFAESAQQMCggFfg4MAiYUBgdYNQQBBA4YC0IWBQQmBRQCAwgEBAIqBQMI/zWe' +
  'NmJvSBYEBBYJBgMOBhYMDBIIAgwEBAsOJggIBASrkgKykgIMEBgRCg0YCggCGBgDBSACHgYEBiIixB25HaV0rnQBNAVYJwUsDBIS' +
  'B0AIAgIGAW4KBAocAQZGBDAMEgQIEgcCDAcYBB4CCA4HFgkMAgsShAECGhACHEYHBAkNOAIGAhIFEhwTRW4kGBwFAwYJLg8cBxAG' +
  'BgEKBAGGAQYYCB4EBAIUAgYCBhIHBgwFDAgWJAQKBgIEBAICAggCBiQBGAMCBg44Ph8cCgIQAhAYGBQhGhIEAiIBBB8asgGPAQEB' +
  'SgEVFA0LBBQPC1QlFAEFHi4pKA84DA4eBN4BCggyATkwBkgHkgKXAgdKXQVeAwEQBCoCDCUBEjIuA0h3FkAUChIkBQsFBBgSGS4L' +
  'SiMOBBw6AgauAQgICA4GAgwGBxgQCB4bBpcd1h0EAgIIEAQBBgoGDgoEAgQEAgIUAqGhAbyhARgWJBgQBB4HAgIKAgoDGgkIPg4I' +
  '4Z0CsEakmgHpb4+KAfp+';

/** Decoded on first lookup, then reused. */
let table: Map<number, number> | null = null;

const decodePacked = (): Map<number, number> => {
  const raw =
    typeof atob === 'function'
      ? Uint8Array.from(atob(PACKED), (c) => c.charCodeAt(0))
      : // Node before atob was global, and any runtime without it.
        new Uint8Array(Buffer.from(PACKED, 'base64'));

  let pos = 0;
  const readVarint = (): number => {
    let result = 0;
    let shift = 0;
    let byte: number;
    do {
      byte = raw[pos++];
      result |= (byte & 0x7f) << shift;
      shift += 7;
    } while (byte & 0x80);
    return result >>> 0;
  };
  // Zigzag: maps signed deltas onto unsigned so small negatives stay one byte.
  const unzigzag = (n: number): number => (n >>> 1) ^ -(n & 1);

  const count = readVarint();

  const sjisDeltas = new Uint16Array(count);
  for (let i = 0; i < count; i++) sjisDeltas[i] = readVarint();

  const map = new Map<number, number>();
  let codePoint = 0;
  let sjis = 0;
  for (let i = 0; i < count; i++) {
    sjis += sjisDeltas[i];
    codePoint += unzigzag(readVarint());
    // First mapping wins, matching how the table was generated.
    if (!map.has(codePoint)) map.set(codePoint, sjis);
  }
  return map;
};

registerKanjiTable((codePoint: number): number | undefined => {
  table ??= decodePacked();
  return table.get(codePoint);
});

/** Number of code points the table covers. Decodes the table if it has not been already. */
export const kanjiTableSize = (): number => {
  table ??= decodePacked();
  return table.size;
};
