import { access, readFile } from 'node:fs/promises';
import path from 'node:path';
import { PROJECT_RECORD_FILE, type ProjectRecord } from '../composition/project';

export type StateStore = 'redux' | 'zustand' | 'none';

export interface ProjectDetection {
  /** Client state store in use. */
  state: StateStore;
  /** Kept for callers that only care whether Redux is present. */
  hasRedux: boolean;
  /** `axios` when the universal client runs on Axios, `both` when the adapter merely ships. */
  httpClient: 'fetch' | 'axios' | 'both' | 'none';
  hasI18n: boolean;
  hasTests: boolean;
  ws: 'none' | 'present';
  hasQuery: boolean;
  hasActions: boolean;
  /** The answers recorded at `init`, when the project was generated by next-maker 5+. */
  record?: ProjectRecord;
}

const exists = async (file: string): Promise<boolean> => {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
};

const readJson = async (file: string): Promise<any | null> => {
  try {
    return JSON.parse(await readFile(file, 'utf-8'));
  } catch {
    return null;
  }
};

/**
 * Describe what a project has. The `.next-maker.json` record written at
 * init is the primary source; the filesystem is consulted so hand-edited
 * projects still work and so a stale record cannot claim a feature that was
 * deleted.
 */
export const detectProjectSetup = async (projectPath: string): Promise<ProjectDetection> => {
  const pkg = await readJson(path.join(projectPath, 'package.json'));
  if (!pkg) throw new Error(`Failed to detect project setup: no package.json in ${projectPath}`);
  const deps: Record<string, string> = { ...pkg.dependencies, ...pkg.devDependencies };
  const record = (await readJson(
    path.join(projectPath, PROJECT_RECORD_FILE),
  )) as ProjectRecord | null;
  const at = (...parts: string[]) => path.join(projectPath, ...parts);

  const storeDir = await exists(at('src', 'store'));
  const hasRedux = !!(deps['@reduxjs/toolkit'] && deps['react-redux']) && storeDir;
  const hasZustand = !!deps.zustand && storeDir && !hasRedux;
  const state: StateStore = hasRedux ? 'redux' : hasZustand ? 'zustand' : 'none';

  const httpCore = await exists(at('src', 'lib', 'http', 'core', 'client.ts'));
  const axiosAdapter =
    !!deps.axios && (await exists(at('src', 'lib', 'http', 'adapters', 'axios.ts')));
  let httpClient: ProjectDetection['httpClient'] = 'none';
  if (httpCore) {
    if (!axiosAdapter) httpClient = 'fetch';
    else {
      let universal = '';
      try {
        universal = await readFile(at('src', 'lib', 'http', 'client.ts'), 'utf-8');
      } catch {
        /* missing universal client */
      }
      httpClient = universal.includes('axiosAdapter') ? 'axios' : 'both';
    }
  }

  const hasI18n = !!deps['next-intl'] && (await exists(at('src', 'i18n')));
  const hasTests = !!deps.vitest || (await exists(at('vitest.config.ts')));
  const ws =
    deps['socket.io-client'] && (await exists(at('src', 'lib', 'ws'))) ? 'present' : 'none';

  return {
    state,
    hasRedux,
    httpClient,
    hasI18n,
    hasTests,
    ws,
    hasQuery: !!deps['@tanstack/react-query'],
    hasActions: !!deps['next-safe-action'],
    record: record ?? undefined,
  };
};
